name: practica-qualentum

services:
  postgres:
    image: postgres:17.4-bookworm
    restart: always
    container_name: database
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - lan
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
  keycloak:
    build:
      context: ./Keycloak
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_USERNAME=Qualentum
      - KC_DB_PASSWORD=Mandarina
      - KC_DB_URL=jdbc:postgresql://database:5432/Keycloak
    networks:
      - lan
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    ports:
      - "8080:8080"
    
  adminer:
    image: adminer
    restart: always
    networks:
      - lan
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    ports:
      - "3000:8080"

volumes:
  db-data:

networks:
  lan:
    driver: bridge
